"use client";

import React from "react";
import { Link } from "@/i18n/navigation";
import { useTranslations } from "next-intl";
import { Calendar, User, ArrowLeft, GitCommit, FileText } from "lucide-react";
import { Article } from "@/types/article";
import ArticleCommunityTabs from "./ArticleCommunityTabs";
import { RevisionDetail } from "@chanomhub/sdk";

export function formatAutoGeneratedDate(dateInput?: string | Date): string {
  if (!dateInput) return "";
  const date = new Date(dateInput);
  if (isNaN(date.getTime())) return "";
  
  const month = date.getMonth() + 1;
  const day = date.getDate();
  const year = date.getFullYear();
  let hours = date.getHours();
  const minutes = String(date.getMinutes()).padStart(2, '0');
  const seconds = String(date.getSeconds()).padStart(2, '0');
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12;
  hours = hours ? hours : 12;
  return `${month}/${day}/${year} ${hours}:${minutes}:${seconds} ${ampm}`;
}

interface ArticleDevlogDetailProps {
  article: Article;
  version: number;
  detail: RevisionDetail | null;
}

const ArticleDevlogDetail: React.FC<ArticleDevlogDetailProps> = ({ article, version, detail }) => {
  const t = useTranslations("ArticleContent");

  const dateStr = detail
    ? new Date(detail.createdAt).toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })
    : "";

  return (
    <div className="min-h-screen bg-[#1b2838] text-[#c6d4df]">
      {/* Header */}
      <div className="bg-[#171a21] pt-6 pb-0">
        <div className="container mx-auto px-4">
          <div className="flex items-center gap-2 text-[#8F98A0] hover:text-white mb-2 text-sm uppercase font-bold tracking-wider">
            <Link href={`/articles/${article.slug}`}>
              {article.title}
            </Link>
            <span>&gt;</span>
            <Link href={`/articles/${article.slug}/devlog`}>
              Devlog
            </Link>
            <span>&gt;</span>
            <span>Version {version}</span>
          </div>
          <h1 className="text-2xl text-white font-medium mb-6 uppercase tracking-widest">
            {detail?.message || `[Auto-generated text]: Update on ${formatAutoGeneratedDate(detail?.createdAt)}.`}
          </h1>
        </div>

        <ArticleCommunityTabs slug={article.slug} />
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="flex items-center justify-between mb-6">
          <Link
            href={`/articles/${article.slug}/devlog`}
            className="flex items-center gap-1.5 text-sm text-[#67c1f5] hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>{t("devlog.backToList")}</span>
          </Link>
        </div>

        {!detail ? (
          <div className="bg-[#1b2838]/50 border border-white/5 rounded p-8 text-center">
            <GitCommit className="w-12 h-12 text-[#4f535c] mx-auto mb-4" />
            <p className="text-[#8f98a0]">Revision details not found.</p>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Revision metadata card */}
            <div className="bg-[#16202d] border border-white/5 rounded-lg p-5 flex flex-col md:flex-row md:items-center justify-between gap-4">
              <div className="space-y-2">
                <div className="flex items-center gap-3">
                  <span className="bg-[#1a9fff]/10 text-[#67c1f5] text-xs font-bold px-2.5 py-1 rounded border border-[#1a9fff]/20">
                    {t("devlog.version", { version: detail.version })}
                  </span>
                  <h2 className="text-white font-medium text-lg">
                    {detail.message || `[Auto-generated text]: Update on ${formatAutoGeneratedDate(detail.createdAt)}.`}
                  </h2>
                </div>

                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[#8f98a0]">
                  <span className="flex items-center gap-1.5">
                    <User className="w-3.5 h-3.5" />
                    {t("devlog.author", { author: detail.author.name })}
                  </span>
                  <span className="flex items-center gap-1.5">
                    <Calendar className="w-3.5 h-3.5" />
                    {t("devlog.date", { date: dateStr })}
                  </span>
                </div>
              </div>
            </div>

            {/* Developer Notes / Patch Notes — Primary Content */}
            <div className="bg-[#16202d] border border-white/5 rounded-lg p-6 space-y-3">
              <h3 className="text-white font-medium text-sm border-b border-white/5 pb-2 uppercase tracking-wide flex items-center gap-2">
                <FileText className="w-4 h-4 text-[#67c1f5]" />
                {t("devlog.developerNotes")}
              </h3>
              {detail.notes ? (
                <div className="text-[#c6d4df] whitespace-pre-wrap leading-relaxed">
                  {detail.notes}
                </div>
              ) : (
                <p className="text-[#8f98a0] italic">
                  {t("devlog.noPatchNotes")}
                </p>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ArticleDevlogDetail;
