"use client";

import React from "react";
import { Link } from "@/i18n/navigation";
import { useTranslations } from "next-intl";
import { GitCommit, Calendar, User, ChevronRight, ArrowLeft, FileText } from "lucide-react";
import { Article } from "@/types/article";
import ArticleCommunityTabs from "./ArticleCommunityTabs";
import { Revision } from "@chanomhub/sdk";

interface ArticleDevlogPageProps {
  article: Article;
  revisions: Revision[];
}

export function formatAutoGeneratedDate(dateInput?: string | Date): string {
  if (!dateInput) return "";
  const date = new Date(dateInput);
  if (isNaN(date.getTime())) return "";
  
  const month = date.getMonth() + 1;
  const day = date.getDate();
  const year = date.getFullYear();
  let hours = date.getHours();
  const minutes = String(date.getMinutes()).padStart(2, '0');
  const seconds = String(date.getSeconds()).padStart(2, '0');
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12;
  hours = hours ? hours : 12;
  return `${month}/${day}/${year} ${hours}:${minutes}:${seconds} ${ampm}`;
}

export function generateDevlogSlug(version: number, message?: string): string {
  if (!message || !message.trim() || message.startsWith("[Auto-generated text]:")) {
    return `update-${version}`;
  }
  return message
    .toLowerCase()
    .trim()
    .replace(/[^\w\s\u0e00-\u0e7f-]/g, "") // support Thai characters + english alpha
    .replace(/[\s_]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const ArticleDevlogPage: React.FC<ArticleDevlogPageProps> = ({ article, revisions = [] }) => {
  const t = useTranslations("ArticleContent");

  // Sort revisions in descending order (newest first)
  const sortedRevisions = [...revisions].sort((a, b) => b.version - a.version);

  return (
    <div className="min-h-screen bg-[#1b2838] text-[#c6d4df]">
      {/* Header */}
      <div className="bg-[#171a21] pt-6 pb-0">
        <div className="container mx-auto px-4">
          <div className="flex items-center gap-2 text-[#8F98A0] hover:text-white mb-2 text-sm uppercase font-bold tracking-wider">
            <Link href={`/articles/${article.slug}`}>
              {article.title}
            </Link>
            <span>&gt;</span>
            <span>Devlog</span>
          </div>
          <h1 className="text-2xl text-white font-medium mb-6 uppercase tracking-widest">
            {article.title} - {t("devlog.title")}
          </h1>
        </div>

        <ArticleCommunityTabs slug={article.slug} />
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="flex items-center gap-2 mb-6">
          <Link
            href={`/articles/${article.slug}`}
            className="flex items-center gap-1.5 text-sm text-[#67c1f5] hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>{t("devlog.backToList")}</span>
          </Link>
        </div>

        {sortedRevisions.length === 0 ? (
          <div className="bg-[#1b2838]/50 border border-white/5 rounded p-8 text-center">
            <GitCommit className="w-12 h-12 text-[#4f535c] mx-auto mb-4" />
            <p className="text-[#8f98a0]">{t("devlog.noRevisions")}</p>
          </div>
        ) : (
          <div className="space-y-6">
            {sortedRevisions.map((revision) => {
              const dateStr = new Date(revision.createdAt).toLocaleDateString(undefined, {
                year: "numeric",
                month: "long",
                day: "numeric",
                hour: "2-digit",
                minute: "2-digit",
              });

              const detailSlug = generateDevlogSlug(revision.version, revision.message);
              const detailUrl = `/articles/${article.slug}/devlog/${revision.version}/${detailSlug}`;

              // Determine if we should truncate notes
              const notesLines = revision.notes ? revision.notes.split("\n") : [];
              const isLongNotes = notesLines.length > 4 || (revision.notes && revision.notes.length > 250);
              
              const displayedNotes = isLongNotes 
                ? notesLines.slice(0, 4).join("\n")
                : revision.notes;

              return (
                <div
                  key={revision.version}
                  className="bg-[#16202d] border border-white/5 rounded-lg p-5 transition-all hover:border-[#67c1f5]/20"
                >
                  <div className="flex flex-col gap-4">
                    {/* Revision Meta Row */}
                    <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-white/5">
                      <div className="flex items-center gap-3 min-w-0">
                        <span className="bg-[#1a9fff]/10 text-[#67c1f5] text-xs font-bold px-2.5 py-1 rounded border border-[#1a9fff]/20 shrink-0">
                          {t("devlog.version", { version: revision.version })}
                        </span>
                        <Link
                          href={detailUrl}
                          className="text-white font-medium text-lg hover:text-[#67c1f5] transition-colors truncate"
                        >
                          {revision.message || `[Auto-generated text]: Update on ${formatAutoGeneratedDate(revision.createdAt)}.`}
                        </Link>
                      </div>

                      <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-[#8f98a0]">
                        <span className="flex items-center gap-1.5">
                          <User className="w-3.5 h-3.5" />
                          {t("devlog.author", { author: revision.author.name })}
                        </span>
                        <span className="flex items-center gap-1.5">
                          <Calendar className="w-3.5 h-3.5" />
                          {t("devlog.date", { date: dateStr })}
                        </span>
                      </div>
                    </div>

                    {/* Developer/Patch Notes */}
                    {revision.notes ? (
                      <div className="text-sm text-[#c6d4df] whitespace-pre-wrap bg-[#111822]/50 p-4 rounded border border-white/5">
                        <div className="text-xs text-[#8f98a0] font-bold uppercase tracking-wider mb-2 flex items-center gap-1.5">
                          <FileText className="w-3.5 h-3.5 text-[#67c1f5]" />
                          <span>{t("devlog.developerNotes")}</span>
                        </div>
                        <div className="leading-relaxed">{displayedNotes}</div>
                        {isLongNotes && (
                          <div className="mt-3 pt-2 border-t border-white/5">
                            <Link
                              href={detailUrl}
                              className="text-[#67c1f5] hover:text-white transition-colors font-semibold text-xs uppercase tracking-wider flex items-center gap-1"
                            >
                              <span>{t("devlog.readMore")}</span>
                              <ChevronRight className="w-3 h-3" />
                            </Link>
                          </div>
                        )}
                      </div>
                    ) : (
                      <div className="text-xs text-[#8f98a0] italic">
                        {t("devlog.noPatchNotes")}
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};

export default ArticleDevlogPage;
