'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { useAppDispatch } from '@/store/hooks';
import { updateFormData, GameUploadFormData } from '@/store/features/upload/uploadSlice';
import { toast } from 'sonner';
import { Clipboard, ClipboardPaste } from 'lucide-react';

export function JsonImportDialog() {
    const dispatch = useAppDispatch();
    const [open, setOpen] = useState(false);
    const [jsonInput, setJsonInput] = useState('');
    const [error, setError] = useState<string | null>(null);

    const handleImport = () => {
        try {
            setError(null);
            if (!jsonInput.trim()) {
                setError('Please paste some JSON data.');
                return;
            }

            const parsedData = JSON.parse(jsonInput);

            // Basic validation: Check if it's an object
            if (typeof parsedData !== 'object' || parsedData === null || Array.isArray(parsedData)) {
                throw new Error('Input must be a valid JSON object.');
            }

            // Dispatch update
            // We cast to any/Partial<GameUploadFormData> to be safe with the dispatch
            dispatch(updateFormData(parsedData as Partial<GameUploadFormData>));

            toast.success('Game data imported successfully!');
            setJsonInput('');
            setOpen(false);
        } catch (e: any) {
            console.error('JSON Import Error:', e);
            setError(e.message || 'Invalid JSON format.');
            toast.error('Failed to import JSON.');
        }
    };

    const handlePasteFromClipboard = async () => {
        try {
            const text = await navigator.clipboard.readText();
            setJsonInput(text);
            setError(null);
            toast.info('Pasted from clipboard');
        } catch (err) {
            console.error('Failed to read clipboard contents: ', err);
            toast.error('Failed to read from clipboard. Please paste manually.');
        }
    };

    const handlePasteSample = () => {
        const sample: Partial<GameUploadFormData> = {
            title: "My Awesome Game",
            creator: "Indie Dev",
            ver: "1.0.0",
            description: "A short description of the game.",
            body: "<p>Detailed HTML content here.</p>",
            engine: "Unity",
            platforms: ["Windows", "Mac"],
            tags: ["Action", "Adventure"],
            categories: ["Indie"],
            downloads: [
                { name: "Mega.nz", url: "https://mega.nz/..." }
            ]
        };
        setJsonInput(JSON.stringify(sample, null, 2));
        setError(null);
    };

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
                <Button variant="outline" className="gap-2">
                    <ClipboardPaste className="h-4 w-4" />
                    Paste JSON
                </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[600px] text-foreground">
                <DialogHeader>
                    <DialogTitle>Import Game Data</DialogTitle>
                    <DialogDescription>
                        Paste the JSON summary generated by your AI tool here.
                    </DialogDescription>
                </DialogHeader>
                <div className="grid gap-4 py-4">
                    <div className="bg-muted/50 p-3 rounded-md text-sm text-muted-foreground border">
                        <p className="font-semibold mb-1">💡 For "body" (Full Description):</p>
                        <p>Please use <strong>HTML format</strong>. Supported tags: headers, paragraphs, lists, bold, italic. Avoid complex styles or inline CSS.</p>
                    </div>
                    <div className="flex justify-end">
                        <Button variant="ghost" size="sm" onClick={handlePasteFromClipboard} className="text-xs h-8 gap-1">
                            <Clipboard className="h-3 w-3" />
                            Paste from Clipboard
                        </Button>
                    </div>
                    <Textarea
                        placeholder="Paste JSON here..."
                        className="min-h-[300px] font-mono text-sm"
                        value={jsonInput}
                        onChange={(e) => {
                            setJsonInput(e.target.value);
                            if (error) setError(null);
                        }}
                    />
                    {error && <p className="text-sm text-red-500">{error}</p>}
                </div>
                <DialogFooter className="sm:justify-between">
                    <Button variant="ghost" onClick={handlePasteSample} type="button">
                        Load Sample
                    </Button>
                    <div className="flex gap-2">
                        <Button variant="outline" onClick={() => setOpen(false)} type="button">
                            Cancel
                        </Button>
                        <Button onClick={handleImport} type="button">
                            Import
                        </Button>
                    </div>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
}
